### ISSUE TITLE
Support BanManager v7

### ISSUE THREAD

**Issue by confuser** [BanManagement/BanManager-WebEnhancer#1]

**Comment by voidpointer0x00** [comment]
Recently pushed v7 support related commit up to fork, but I have problem with Jenkins repository for a new 7.* versions: there are no packaged .jar files for BanManager artifact, so I am getting maven dependency errors when I'm trying to add it to project in order to be able to use bukkit defined Events.

**Comment by confuser** [comment]
@NyanGuyMF You'll need to depend upon BanManagerBukkit instead, https://banmanagement.com/developers

**Comment by voidpointer0x00** [comment]
@confuser Oh, great, thanks a lot) Now that works perfectly
